name: Build and Deploy

on:
  workflow_dispatch:

jobs:
  deploy-frontend:
    runs-on: ubuntu-latest
    env:
      REACT_APP_SERVER_BASE_URL: ${{ secrets.REACT_APP_SERVER_BASE_URL }}

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Install Frontend Dependencies
        working-directory: frontend
        run: yarn install

      - name: Frontend Production Build
        working-directory: frontend
        run: yarn build
